### PR TITLE
fix for php 8.3 in alpine 3.19

### PR DESCRIPTION
**Pull request by dormancygrace**

### CODE REVIEW

**Comment by GaryAllan** [comment]
Hello @dormancygrace 

Thank you. I've uploaded a fix for php82.

**Comment by dormancygrace** [comment]
but alpine 3.19 uses php 8.3

**Comment by GaryAllan** [comment]
image

**Comment by dormancygrace** [comment]
sorry for this =)

**Comment by GaryAllan** [comment]
Thanks. You noticed the issue and prompted me to fix it.

**Pull request closed without merging**
